In [3]:
import numpy as np
d = 64                           # 向量维度
nb = 100000                      # 数据库大小（向量数量）
nq = 10000                       # 查询数量
np.random.seed(1234)             # 设置随机种子，确保结果可复现

# 生成随机数据
xb = np.random.random((nb, d)).astype('float32')    # 生成数据库向量
print(xb)
xb[:, 0] += np.arange(nb) / 1000.                   # 给第一维添加一个小的线性增长
print(xb)
xq = np.random.random((nq, d)).astype('float32')    # 生成查询向量
xq[:, 0] += np.arange(nq) / 1000.                   # 给第一维添加一个小的线性增长
print(xq)


[[0.19151945 0.62210876 0.43772775 ... 0.62491673 0.4780938  0.19567518]
 [0.38231745 0.05387368 0.4516484  ... 0.15139526 0.33517465 0.65755177]
 [0.07334255 0.0550064  0.3231948  ... 0.34441698 0.6408804  0.12620533]
 ...
 [0.81447345 0.5902453  0.7988935  ... 0.339859   0.3019495  0.85385454]
 [0.6714615  0.9160688  0.9550788  ... 0.59536433 0.03849181 0.10563799]
 [0.85663575 0.59113413 0.67890793 ... 0.21897699 0.06530159 0.21753833]]
[[1.91519454e-01 6.22108757e-01 4.37727749e-01 ... 6.24916732e-01
  4.78093803e-01 1.95675179e-01]
 [3.83317441e-01 5.38736843e-02 4.51648414e-01 ... 1.51395261e-01
  3.35174650e-01 6.57551765e-01]
 [7.53425434e-02 5.50063960e-02 3.23194802e-01 ... 3.44416976e-01
  6.40880406e-01 1.26205325e-01]
 ...
 [1.00811470e+02 5.90245306e-01 7.98893511e-01 ... 3.39859009e-01
  3.01949501e-01 8.53854537e-01]
 [1.00669464e+02 9.16068792e-01 9.55078781e-01 ... 5.95364332e-01
  3.84918079e-02 1.05637990e-01]
 [1.00855637e+02 5.91134131e-01 6.78907931e-01 ... 2.189

In [4]:
import faiss
index = faiss.IndexFlatL2(d)   # 创建使用L2距离的索引
print(index.is_trained)        # 检查索引是否需要训练（对于简单的IndexFlatL2不需要）
index.add(xb)                  # 将向量添加到索引中
D, I = index.search(xq, k=4)   # 对每个查询向量搜索4个最近邻
print(D[:5])
print(I[:5])                   # 打印前5个查询的结果   

True
[[6.815506  6.8894653 7.3956795 7.4290257]
 [6.6041107 6.679695  6.7209625 6.828682 ]
 [6.4703865 6.8578606 7.0043755 7.036564 ]
 [5.573681  6.407543  7.1395226 7.3555984]
 [5.409401  6.232216  6.4173393 6.5743637]]
[[ 381  207  210  477]
 [ 526  911  142   72]
 [ 838  527 1290  425]
 [ 196  184  164  359]
 [ 526  377  120  425]]
